version: 0.2.0.{build}
branches:
  only:
  - master
configuration: Release
clone_depth: 1
nuget:
  disable_publish_on_pr: true
before_build:
- ps: .\tools\nuget\nuget.exe restore .\Positron.sln
build:
  parallel: true
  verbosity: normal
after_build:
- ps: .\tools\nuget\pack.ps1
artifacts:
- path: packaging/*.nupkg
  name: Nuget
deploy:
- provider: NuGet
  api_key:
    secure: KzT1ESVyB5LB0Ovg+dPUmvZYQJ0XYoBEe9DW1pBDKzv0y/7y2RlJ1xt16ZI5dnVE
  artifact: Nuget
  on:
    APPVEYOR_REPO_TAG: true
notifications:
- provider: GitHubPullRequest
  auth_token:
    secure: ULHzhdaGoUWJwQqameGnvmg+61OInc0YMit2rTezp2pi3ZB4ehCq4T0h3WbnVEcu
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true